# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/20_MERFISH_visualization.ipynb (unless otherwise specified).

__all__ = ['make_roc', 'match_bench', 'plot_gene_numbers']

# Cell
from ..imports import *
from .file_io import *
from .emitter_io import *
from .utils import *
from .dataset import *
from .plotting import *
from ..engine.noise import estimate_noise_scale
import shutil
from .visualization import *
from .predict import predict

from numba import njit
from scipy.spatial import cKDTree
from .evaluation import matching

import io, requests
from sklearn.neighbors import NearestNeighbors
from starfish import data
import pprint

# Cell
def make_roc(df, var='code_err', ascending=True):

    x = np.arange(1000,len(df),100)
    df = df.sort_values(var, ascending=ascending)
    n_blanks = []
    for i in x:
        n_blanks.append((df[:int(i)]['gene'].str.contains('Blank')).sum())

    return x, n_blanks

# Cell
def match_bench(pred_df, bench_df):

    pred_df = pred_df.copy()

    bench_match = bench_df.copy()
    bench_match.loc[:,'frame_idx'] = 0
    bench_match.loc[:,'loc_idx'] = np.arange(len(bench_match))
    bench_match.loc[:,'int'] = bench_match['total_magnitude']
    bench_match.loc[:,'z'] = 50/100
    bench_match = px_to_nm(bench_match)

    pred_df.loc[:,'frame_idx'] = 0

    _,_,shift = matching(bench_match, pred_df, tolerance=250, print_res=False)
    print(shift)
    bench_match = shift_df(bench_match, shift=-np.array(shift))

    _,_,shift = matching(bench_match, pred_df, tolerance=250, print_res=False)

    bench_match = shift_df(bench_match, shift=-np.array(shift))
    _,matches,shift = matching(bench_match, pred_df, tolerance=250, print_res=True)

    matches['gene_pred'] = \
        pred_df.set_index('loc_idx').loc[list(np.array(matches['pred_idx'].values, dtype='int'))]['gene'].values
    matches['gene_tar'] = \
        bench_match.set_index('loc_idx').loc[list(np.array(matches['tar_idx'].values, dtype='int'))]['gene'].values

    return matches, bench_match

# Cell
def plot_gene_numbers(bench_counts, res_counts, title='', log=True, corr=True):

    if corr:
        r = np.corrcoef(bench_counts, res_counts)[0, 1]
        r = np.round(r, decimals=3)
    else:
        r = np.sum(res_counts)
    x_lim = np.max([bench_counts.max(), res_counts.max()])
    x = np.linspace(0, x_lim)

    plt.scatter(bench_counts, res_counts, 50, zorder=2)
    plt.plot(x, x, '-k', zorder=1)

    plt.xlabel('Gene copy number Benchmark')
    plt.ylabel('Gene copy number DECODE')
    if log:
        plt.xscale('log')
        plt.yscale('log')
    plt.title(f'{title} r = {r}');