wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.7.7
      5: 0.10.23
      8:
      - 1
      - 5
dataset:
  desc: null
  value: w1_HelaKyoto_Gapdh_2597_p01_cy3__Cell_CP_14__cell3D__1
learning_rate:
  desc: null
  value: 0.0005
