# @package _global_
genm:
    exp_type:
        n_channels: 16
        n_bits: 4
        n_genes: 140
        slice_rec: True
        pred_z: True
        sm_fish_ch: 
        sample_from_codebook: True
        const_theta_sim: False
        phasing: False
        
data_path:
    psf_path: /groups/turaga/home/speisera/Mackebox/Artur/WorkDB/deepstorm/decode_fish/figures/MF_psf.tif
    image_path: ${base_dir}/datasets/CodFish/MERFISH/starfish_scaled/img_stack.tiff

codebook:
    _target_: decode_fish.funcs.exp_specific.get_benchmark