# @package _global_
genm:
    exp_type:
        n_channels: 22
        n_genes: 252
        n_bits: 4
        slice_rec: True
        pred_z: True
        sm_fish_ch: 
        sample_from_codebook: True
        const_theta_sim: False
        phasing: False
        
data_path:
    psf_path: /groups/turaga/home/speisera/Mackebox/Artur/WorkDB/deepstorm/decode_fish/figures/MF_psf.tif
    image_proc:
        crop_sl: s_[:,:,:,:]
        override:
            _target_: decode_fish.funcs.exp_specific.read_MOp_tiff 
    
codebook:
    _target_: decode_fish.funcs.exp_specific.get_merfish_mop
    n_genes: 252