# @package _global_
genm:
    exp_type:
        n_channels: 22
        n_genes: 252
        n_bits: 4
        slice_rec: True
        pred_z: True
        sm_fish_ch: 
        sample_from_codebook: True
        const_theta_sim: False
        phasing: False
        int_inf: 'per_channel'
    microscope:
        ch_cols: [0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0]
    PSF:
        n_cols: 2
        
network:
    is_2D: False
        
data_path:
    psf_path: /groups/turaga/home/speisera/Mackebox/Artur/WorkDB/deepstorm/decode_fish/figures/MF_psf2.tif
    image_proc:
        crop_sl: s_[:,:,:,:]
        override:
            _target_: decode_fish.funcs.exp_specific.read_MOp_tiff 
            scaled: True
            z_to_batch: ${network.is_2D}
            
codebook:
    _target_: decode_fish.funcs.exp_specific.get_mop_codebook

evaluation:
    code_stats: 
        enabled: True
        path: /groups/turaga/home/speisera/Mackebox/Artur/WorkDB/deepstorm/decode_fish/data/MOp_eval_ztb/
        eval_func:
            _target_: decode_fish.funcs.exp_specific.exp_train_eval_MOp 
            
    